// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vxsbdmogiouqddpxfvqx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ4c2JkbW9naW91cWRkcHhmdnF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg4NDM2NTUsImV4cCI6MjA2NDQxOTY1NX0.JALKxSIKjx2nmkXuhhrZ0N9xrtK_Fm5I9gQj5VnFd7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);